# Note: Parameters can be hardcoded directly in 'deploy-functions.yaml'
# if you do not need to vary them between your functions!
description: "Function to calculate OEE"
owner: CDF Bootcamp Team 07
cpu: 1.0
memory: 1.5
data_set_id: 8519575910024297
